/*
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.aevi.sdk.flow.model;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.aevi.util.json.JsonConverter;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a paying customer with associated customer details and tokens.
 */
public class Customer extends BaseModel {

    private String fullName;
    private final AdditionalData customerDetails;
    private final List<Token> tokens;

    // Default constructor for deserialisation
    Customer() {
        super(null);
        fullName = null;
        customerDetails = new AdditionalData();
        tokens = new ArrayList<>();
    }

    /**
     * Create a new Customer instance with a unique id.
     *
     * @param id The unique id
     */
    public Customer(String id) {
        super(id);
        customerDetails = new AdditionalData();
        tokens = new ArrayList<>();
    }

    /**
     * Get the customer id.
     *
     * This identifier is bespoke to the application that created the Customer and there are no guarantees that it is unique across Customers
     * generated by different applications.
     *
     * @return The customer id
     */
    @NonNull
    @Override
    public String getId() {
        return super.getId();
    }

    /**
     * Get the full name for this customer.
     *
     * Please see the customer details for name broken down into first name, surname, middle names, etc.
     *
     * @return The customer full name, or null if not set.
     */
    @Nullable
    public String getFullName() {
        return fullName;
    }

    /**
     * Set the full name for the Customer. See {@link #constructFullName(String, String[], String)} for assistance.
     *
     * @param fullName The customer full name.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Convenience wrapper for adding additional customer data.
     *
     * This can be used to set arbitrary data to be passed on in the request to down-stream flow apps and/or payment apps.
     *
     * See {@link AdditionalData#addData(String, Object[])} for more info.
     *
     * @param key    The key to use for this data
     * @param values An array of values for this data
     * @param <T>    The type of object this data is an array of
     */
    public <T> void addCustomerDetails(String key, T... values) {
        customerDetails.addData(key, values);
    }

    /**
     * Get the optional customer details, such as phone number, address, etc.
     *
     * @return The Options representing customer details. May be empty.
     */
    @NonNull
    public AdditionalData getCustomerDetails() {
        return customerDetails;
    }

    /**
     * Add a customer token.
     *
     * @param token Token to add
     */
    public void addToken(Token token) {
        tokens.add(token);
    }

    /**
     * Retrieve the list of tokens associated with this customer.
     *
     * @return The list of token. May be empty.
     */
    @NonNull
    public List<Token> getTokens() {
        return tokens;
    }

    @Override
    public String toJson() {
        return JsonConverter.serialize(this);
    }

    @Override
    public boolean equals(Object o) {
        return doEquals(o, false);
    }

    @Override
    public boolean equivalent(Object o) {
        return doEquals(o, true);
    }

    private boolean doEquals(Object o, boolean equiv) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        if (equiv && !super.doEquivalent(o)) {
            return false;
        } else if (!equiv && !super.equals(o)) {
            return false;
        }

        Customer customer = (Customer) o;

        if (fullName != null ? !fullName.equals(customer.fullName) : customer.fullName != null) {
            return false;
        }
        if (customerDetails != null ? !customerDetails.equals(customer.customerDetails) : customer.customerDetails != null) {
            return false;
        }
        return tokens != null ? tokens.equals(customer.tokens) : customer.tokens == null;
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + (fullName != null ? fullName.hashCode() : 0);
        result = 31 * result + (customerDetails != null ? customerDetails.hashCode() : 0);
        result = 31 * result + (tokens != null ? tokens.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "fullName='" + fullName + '\'' +
                '}';
    }

    public static Customer fromJson(String json) {
        return JsonConverter.deserialize(json, Customer.class);
    }

    /**
     * Construct a full name from the provided first name, middle names and surname fields.
     *
     * Example - "John", ["Steve"], "Doe" returns "John Steve Doe".
     *
     * First name at a minimum is mandatory.
     *
     * @param firstName   First name
     * @param middleNames Middle names
     * @param surname     Surname
     * @return The full name, or empty string if name fields are not set.
     */
    public static String constructFullName(String firstName, String[] middleNames, String surname) {

        if (firstName == null) {
            return "";
        }

        StringBuilder nameBuilder = new StringBuilder();
        nameBuilder.append(firstName);
        nameBuilder.append(' ');
        if (middleNames != null) {
            for (String middleName : middleNames) {
                nameBuilder.append(middleName);
                nameBuilder.append(' ');
            }
        }
        if (surname != null) {
            nameBuilder.append(surname);
        }
        return nameBuilder.toString();
    }

    public static Customer clone(Customer customer) {
        Customer newCustomer = new Customer(customer.getId());
        newCustomer.setFullName(customer.getFullName());
        newCustomer.getTokens().addAll(customer.getTokens());
        newCustomer.getCustomerDetails().addData(customer.getCustomerDetails(), true);
        return newCustomer;
    }

}
